### ISSUE TITLE
[ REFACTOR ] 리팩토링 계획

### ISSUE THREAD

**Issue by Hansebin** [Hansebin/finca-project#1]
### Finca 프로젝트 리팩토링
- 디렉토리 구조 정리의 필요성과 코드의 복잡성 등의 이유들로 리팩토링을 계획함.
- 컴포넌트 구조를 좀 더 세부적으로 나누고, 불필요한 전역 상태를 제거하고 스타일링 코드를 일관성이 있게 통일하는 것이 가장 큰 목표
- 더불어, zod 라이브러리를 사용해서 스키마 정의 및 유효성 검사 함께 진행
- Recoil -> Redux로 상태 관리 변경

### ToDo
- [x] Plan : 리팩토링 계획 issue 작성
- [x] TypeScript : type 선언 방식 변경 (type -> interface)
- [x] TypeScript : zod 라이브러리 도입
- [ ] TypeScript : zod 유효성 검사
- [ ] Style : tailwind로 스타일링 코드 전체적으로 수정
- [ ] Status : 불필요한 전역 상태 제거
- [ ] Status : Recoil -> Redux로 상태 관리 라이브러리 변경
- [ ] Components : 컴포넌트 세부적으로 분리 및 클린 코드

### etc
- 12월 31일을 목표로 1차 리팩토링 마무리
- TypeScript : 객체 타입의 경우 interface 선언 방식 사용 / 기존 객체 타입에서 확장 등이 된 경우 type 사용
