### ISSUE TITLE
[PLAN] 01.04 리팩토링 계획 

### ISSUE THREAD

**Issue by Hansebin** [Hansebin/finca-project#2]
## Description
리팩토링 계획 구체화

## To-Do
- [ ] styled-component로 작업한 코드 모두 tailwindCSS로 변경
- [ ] 디렉토리 구조 변경 -> 코드의 목적과 의도에 따라 한눈에 파악 가능하도록
- [ ] 재사용성 높이기 위해 컴포넌트 분리 -> 최소 하나의 작업만 가능하도록 함수로 분리
- [ ] TypeScript 코드 수정
- [ ] zod 라이브러리 사용으로 유효성 검사 강화
- [ ] recoil zustand로 변경 -> recoil maintain 문제가 있다고 판단
- [ ] maintain 문제성이 있는 라이브러리 변경 혹은 제거 후 직접 구현 (ex. 페이지네이션)
- [ ] RSC가 필요한 부분 RSC 사용

## ETC
작업하다가 필요한 부분 생기면 추가할 예정 🙂
